run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - exportloopref
    - gocheckcompilerdirectives
    # conditionally enable this on linux/macos
    # - gofmt
    # - goimports
    - intrange
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - testifylint
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - usestdlibvars
severity:
  default-severity: error
  rules:
    - linters:
        - gofmt
        - goimports
        - intrange
        - usestdlibvars
      severity: info
